server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
       - id: payment_routh             # 路由的ID，没有固定规则但要求唯一，建议配合服务名
         # uri: http://localhost:8001    # 匹配提供服务的路由地址
         uri: lb://CLOUD-PAYMENT-SERVICE
         predicates:
          - Path=/payment/**           # 断言，路径相匹配的进行路由
          - After=2020-05-25T16:55:00.889+08:00[Asia/Shanghai]    # 断言，在该时间之后，访问才生效
          # - Before=2020-05-25T16:55:00.889+08:00[Asia/Shanghai] # 断言，在该时间之前，访问才生效
          # - Between=2020-05-25T16:55:00.889+08:00[Asia/Shanghai], 2020-05-26T16:55:00.889+08:00[Asia/Shanghai]   # 断言，在这两个时间之间，访问才生效
          # - Cookie=username, fion      # 断言，Cookie中需要有username=fion才生效
          # - Header=X-Request-Id, \d+     # 断言，Header中需要有X-Request-Id，且值为整数才生效
      discovery:
        locator:
          enabled: true                # 开启从注册中心动态创建路由的功能，利用微服务进行路由


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: cloud-gateway-service