server:
  port: 83

spring:
  application:
    name: nacos-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

# 消费者将要访问的微服务名称，需要成功注册进nacos
service-url:
  nacos-payment-service: http://nacos-payment-service
