server:
  port: 9003

spring:
  application:
    name: nacos-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.226.47:3306/clouddb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: fion
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fion.springcloud.entity

management:
  endpoints:
    web:
      exposure:
        include: "*"
