server:
  port: 80

spring:
  application:
    name: cloud-order-hystrix-order-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 设置feign客户端超时时间
ribbon:
  # 指的是建立连接后，从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  # 指的是建立连接所用的时间
  ConnectTimeout: 5000

# 开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true